# Generated by Django 5.1.4 on 2025-02-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
