# Generated by Django 5.1.4 on 2025-04-07 07:35

import auth_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_groupchat_groupmessage_messageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=auth_app.models.group_message_attachment_path)),
                ('file_type', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='auth_app.groupmessage')),
            ],
        ),
    ]
