# Generated by Django 5.1.4 on 2025-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_userreport_friendrequest_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
