# Generated by Django 5.1.2 on 2025-04-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
